const pokemonTypes = {
  FETCH_POKEMONS_START: 'FETCH_POKEMONS_START',
  FETCH_POKEMONS_SUCCESS: 'FETCH_POKEMONS_SUCCESS',
  FETCH_POKEMONS_FAILED: 'FETCH_POKEMONS_FAILED',
  FETCH_POKEMON_START: 'FETCH_POKEMON_START',
  FETCH_POKEMON_SUCCESS: 'FETCH_POKEMON_SUCCESS',
  FETCH_POKEMON_FAILED: 'FETCH_POKEMON_FAILED',
  CATCH_POKEMON: 'CATCH_POKEMON',
  RELEASE_POKEMON: 'RELEASE_POKEMON',
  RELEASE_ALL: 'RELEASE_ALL'
};

export default pokemonTypes;
